### Extracting Query
GET http://localhost:3000/q?id=100


### Extracting requestBody
POST http://localhost:3000/q
content-type: application/json

{
  "id": 200
}


### Extracting requestBody
POST http://localhost:3000/both?id=1
content-type: application/json

{
  "id": 200
}

### Receive Cookie
GET http://localhost:3000/set_cookie


### Extracting Cookie
GET http://localhost:3000/c
content-type: application/json
Cookie: sid=1200


### Extracting No Cookie
GET http://localhost:3000/c
content-type: application/json


### Extracting Cookie and Query
GET http://localhost:3000/cq?id=500
content-type: application/json
Cookie: sid=499


### Websocket upgrade?
GET http://localhost:3000/websocket
Sec-WebSocket-Version: 13
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: 0n5rjz+0mWyreQf5sdLxbQ==
Connection: keep-alive, Upgrade
Upgrade: websocket


### get user list
GET http://localhost:3000/api/user
